Controllers/BookOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SrmBook.Data;
using SrmBook.Models;

namespace SrmBook.Controllers
{
    public class BookOrderController : Controller
    {
        private readonly BookOrderContext _context;

        public BookOrderController(BookOrderContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string searchString, string searchStr, DateTime? searchDate, int? orderPage, int? inventoryPage)
        {
            int itemsPerPage = 5; // 페이지당 항목 수
            int orderCurrentPage = orderPage ?? 1; // 발주 페이지 (기본값: 1)
            int inventoryCurrentPage = inventoryPage ?? 1; // 재고 페이지 (기본값: 1)

            // 로그인한 사용자의 정보를 세션에서 가져옴
            var userType = HttpContext.Session.GetString("USER_TYPE_KEY");
            var currentUser = HttpContext.Session.GetString("USER_SESSION_KEY");

            // 발주 검색
            var bookOrders = await SearchBookOrders(searchString, searchDate, userType, currentUser);
            // 재고 검색
            var bookInventorys = await SearchInventory(searchStr);

            // 페이징 처리 - bookOrders
            var totalOrderItems = bookOrders.Count();
            var pagedBookOrders = bookOrders.Skip((orderCurrentPage - 1) * itemsPerPage).Take(itemsPerPage);

            // 페이징 처리 - bookInventory
            var totalInventoryItems = bookInventorys.Count();
            var pagedBookInventory = bookInventorys.Skip((inventoryCurrentPage - 1) * itemsPerPage).Take(itemsPerPage);

            // 복합 ViewModel에 데이터 할당
            var bookComposite = new BookComposite
            {
                BookOrders = pagedBookOrders,
                BookInventory = pagedBookInventory,
                OrderPageInfo = new PageInfo
                {
                    TotalItems = totalOrderItems,
                    CurrentPage = orderCurrentPage,
                    ItemsPerPage = itemsPerPage
                },
                InventoryPageInfo = new PageInfo
                {
                    TotalItems = totalInventoryItems,
                    CurrentPage = inventoryCurrentPage,
                    ItemsPerPage = itemsPerPage
                }
            };

            return View(bookComposite);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BookOrder == null)
            {
                return NotFound();
            }

            var bookOrder = await _context.BookOrder
                .FirstOrDefaultAsync(m => m.ORDER_NUM == id);
            if (bookOrder == null)
            {
                return NotFound();
            }

            return View(bookOrder);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ORDER_NUM,USER_ID,ORDER_DATE,BOOK_QUANTITY,TOTAL_PRICE,BOOK_NAME,BOOK_NUM")] BookOrder bookOrder)
        {
            if (ModelState.IsValid)
            {
                // 발주 시 도서 재고에 있는 도서 제목과 도서 번호가 일치하는지 확인
                var bookInventory = await _context.BookInventory.FirstOrDefaultAsync(b => b.BOOK_NAME == bookOrder.BOOK_NAME && b.BOOK_NUM == bookOrder.BOOK_NUM);

                if (bookInventory == null)
                {
                    ModelState.AddModelError(string.Empty, "도서 제목이나 도서 번호를 확인해주세요");
                    return View(bookOrder);
                }
                else
                {
                    // 재고 수량 감소
                    bool isStockAvailable = await DecreaseBookInventory(bookOrder.BOOK_NUM, bookOrder.BOOK_QUANTITY);

                    if (!isStockAvailable)
                    {
                        ModelState.AddModelError(string.Empty, "재고가 부족하여 구매할 수 없습니다");
                        return View(bookOrder);
                    }
                    // 가격 계산
                    bookOrder.TOTAL_PRICE = await CalculateTotalPrice(bookOrder.BOOK_NUM, bookOrder.BOOK_QUANTITY);
                    _context.Add(bookOrder);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(bookOrder);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BookOrder == null)
            {
                return NotFound();
            }

            var bookOrder = await _context.BookOrder
                .FirstOrDefaultAsync(m => m.ORDER_NUM == id);
            if (bookOrder == null)
            {
                return NotFound();
            }

            return View(bookOrder);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BookOrder == null)
            {
                return Problem("Entity set 'BookOrderContext.BookOrder'  is null.");
            }

            var bookOrder = await _context.BookOrder.FindAsync(id);
            if (bookOrder != null)
            {
                _context.BookOrder.Remove(bookOrder);
            }
            //재고 수량 증가
            await IncreaseBookInventory(bookOrder.BOOK_NUM, bookOrder.BOOK_QUANTITY);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //발주 확인 메소드
        public async Task<IActionResult> ConfirmOrder(int orderId)
        {
            var order = await _context.BookOrder.FindAsync(orderId);

            if (order == null)
            {
                // 발주가 존재하지 않을 경우 에러 처리
                return NotFound();
            }

            order.ORDER_CONFIRMED = true;

            _context.Entry(order).Property(x => x.ORDER_CONFIRMED).IsModified = true;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool BookOrderExists(int id)
        {
            return _context.BookOrder.Any(e => e.ORDER_NUM == id);
        }

        // 총 가격 계산 메소드
        private async Task<decimal> CalculateTotalPrice(int bookNum, int quantity)
        {
            var bookInventory = await _context.BookInventory.FindAsync(bookNum);
            if (bookInventory != null)
            {
                return bookInventory.BOOK_PRICE * quantity;
            }
            return 0;
        }

        //재고 수량 감소
        private async Task<bool> DecreaseBookInventory(int bookNum, int quantity)
        {
            var bookInventory = await _context.BookInventory.FindAsync(bookNum);
            if (bookInventory != null)
            {
                if (bookInventory.BOOK_QUANTITY >= quantity)
                {
                    bookInventory.BOOK_QUANTITY -= quantity;
                    _context.BookInventory.Update(bookInventory);
                    await _context.SaveChangesAsync();
                    return true; // 재고 충분하여 구매 가능
                }
            }
            return false; // 재고 부족으로 구매 불가능
        }

        //재고 수량 증가
        private async Task IncreaseBookInventory(int bookNum, int quantity)
        {
            var bookInventory = await _context.BookInventory.FindAsync(bookNum);
            if (bookInventory != null)
            {
                bookInventory.BOOK_QUANTITY += quantity;
                _context.BookInventory.Update(bookInventory);
                await _context.SaveChangesAsync();
            }
        }
        
        //발주 검색 메소드
        private async Task<List<BookOrder>> SearchBookOrders(string searchString, DateTime? searchDate, string userType, string currentUser)
        {
            var bookOrders = _context.BookOrder.AsQueryable();

            if (IsAdminUser(userType))
            {
                // 관리자인 경우 모든 발주를 반환
                bookOrders = bookOrders.Where(s => true);
            }
            else
            {
                // 일반 사용자인 경우 해당 사용자의 발주만 필터링
                bookOrders = bookOrders.Where(s => s.USER_ID == currentUser);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                bookOrders = bookOrders.Where(s => s.BOOK_NAME.Contains(searchString));
            }

            if (searchDate.HasValue)
            {
                DateTime startDate = searchDate.Value.Date;
                DateTime endDate = searchDate.Value.AddDays(1).Date;
                bookOrders = bookOrders.Where(s => s.ORDER_DATE >= startDate && s.ORDER_DATE < endDate);
            }

            return await bookOrders.ToListAsync();
        }

        private bool IsAdminUser(string userType)
        {
            // 세션을 통해 현재 사용자가 관리자인지 여부를 판별
            // 예시: 세션에서 userType 값이 "admin"인 경우에만 관리자로 판별
            return userType == "admin";
        }

        //재고 검색 메소드
        private async Task<List<BookInventory>> SearchInventory(string searchStr)
        {
            var BookInventory = from m in _context.BookInventory
                                select m;

            if (!String.IsNullOrEmpty(searchStr))
            {
                BookInventory = BookInventory.Where(s => s.BOOK_NAME.Contains(searchStr));
            }
            return await BookInventory.ToListAsync();
        }

    }
}

Controllers/BookUserController.cs
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SrmBook.Data;
using SrmBook.Models;


namespace SrmBook.Controllers
{
    public class BookUserController : Controller
    {
        private readonly BookUserContext _context;

        public BookUserController(BookUserContext context)
        {
            _context = context;
        }
        // 회원 가입
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(BookUser model)
        {
            if (ModelState.IsValid)
            {
                //id중복체크
                if (IsIdDuplicate(model.USER_ID))
                {
                    ModelState.AddModelError("USER_ID", "이미 사용 중인 아이디입니다.");
                    return View(model);
                }
                // 비밀번호 암호화
                string hashedPassword = HashPassword(model.USER_PW);
                model.USER_PW = hashedPassword;
                _context.BookUser.Add(model);
                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
        // 회원 정보
        public IActionResult Index()
        {
            var users = _context.BookUser.ToList();
            return View(users);
        }
        // 로그인
        [HttpGet]
        public IActionResult Login()
        {
            var model = new LoginView();
            return View(model);
        }
        [HttpPost]
        public IActionResult Login(LoginView model)
        {
            var user = _context.BookUser.FirstOrDefault(u => u.USER_ID == model.USER_ID);

            if (user == null || !VerifyPassword(model.USER_PW, user.USER_PW))//암호화된 비밀번호 검증
            {
                ModelState.AddModelError(string.Empty, "아이디 또는 비밀번호가 잘못되었습니다.");
                return View();
            }

            HttpContext.Session.SetString("USER_TYPE_KEY", user.USER_TYPE); // 권한 세션
            HttpContext.Session.SetString("USER_SESSION_KEY", user.USER_ID); // 세션

            return RedirectToAction("Index", "Home");
        }
        // 로그아웃
        public IActionResult Logout()
        { 
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        // 회원 수정
        [HttpGet]
        public IActionResult Edit(int userNum)
        {
            var user = _context.BookUser.FirstOrDefault(u => u.USER_NUM == userNum);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(BookUser model)
        {
            if (ModelState.IsValid)
            {
                //비밀번호 암호화
                string hashedPassword = HashPassword(model.USER_PW);
                model.USER_PW = hashedPassword;
                _context.Entry(model).State = EntityState.Modified;
                _context.SaveChanges();
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
        // 회원 삭제
        [HttpGet]
        public IActionResult Delete(int userNum)
        {
            var user = _context.BookUser.FirstOrDefault(u => u.USER_NUM == userNum);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        [HttpPost]
        public IActionResult DeleteConfirmed(BookUser model)
        {
            var user = _context.BookUser.FirstOrDefault(u => u.USER_NUM == model.USER_NUM);

            if (user == null)
            {
                return NotFound();
            }

            _context.BookUser.Remove(user);
            _context.SaveChanges();
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        // 비밀번호 암호화
        private string HashPassword(string password)
        {
            byte[] salt = new byte[128 / 8]; // 솔트 생성
            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(salt);
            }

            string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: password,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA256,
                iterationCount: 10000,
                numBytesRequested: 256 / 8));

            return $"{Convert.ToBase64String(salt)}.{hashed}";
        }

        // 비밀번호 검증
        private bool VerifyPassword(string password, string hashedPassword)
        {
            string[] parts = hashedPassword.Split('.', 2);
            if (parts.Length != 2)
            {
                return false;
            }

            byte[] salt = Convert.FromBase64String(parts[0]);
            string hashed = parts[1];

            string rehashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: password,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA256,
                iterationCount: 10000,
                numBytesRequested: 256 / 8));

            return hashed == rehashed;
        }
        //id중복체크
        private bool IsIdDuplicate(string Id)
        {
            return _context.BookUser.Any(u => u.USER_ID == Id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
    var Key = Context.Session.GetString("USER_SESSION_KEY");
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SrmBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.0/dist/cerulean/bootstrap.min.css" rel="stylesheet">
</head>

<body style="background-color: black;">
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">SRMBOOK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
                    aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                aria-haspopup="true" aria-expanded="false">회원관리</a>
                            <div class="dropdown-menu">
                                @if (Key == null)
                                {
                                    <a class="dropdown-item" asp-controller="BookUser" asp-action="Login">로그인</a>
                                    <a class="dropdown-item" asp-controller="BookUser" asp-action="Register">회원가입</a>
                                }

                                else
                                {
                                    <a class="dropdown-item" asp-controller="BookUser" asp-action="Index">회원정보 수정</a>
                                }
                            </div>
                        </li>
                        @if (Key != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                    aria-haspopup="true" aria-expanded="false">도서 분류</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="BookClassification" asp-action="Index">도서
                                        분류</a>
                                    <a class="dropdown-item" asp-controller="BookInventory" asp-action="Index">도서 재고</a>
                                </div>
                            </li>
                        }
                        @if (Key != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                    aria-haspopup="true" aria-expanded="false">도서 발주 / 배송</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="BookOrder" asp-action="Index">도서 발주 및 내역</a>
                                    <a class="dropdown-item" asp-controller="BookDelivery" asp-action="Index">배송 및 내역</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <!-- 로그아웃 버튼 -->
            @if (Key != null)
            {
                <div class="btn-group container-fluid" style="width:170px; height:30px;" role="group"
                    aria-label="Basic example">
                    <button class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#logoutModal">로그아웃</button>
                </div>
            }
            <!-- 로그아웃 모달 -->
            <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="logoutModalLabel">로그아웃 확인</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>정말로 로그아웃 하시겠습니까?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                            <button type="button" class="btn btn-secondary" id="logoutButton">로그아웃</button>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(function () {
            // 로그아웃 버튼 클릭 이벤트 처리
            $('#logoutButton').on('click', function () {
                // 로그아웃 요청 처리
                $.ajax({
                    url: '/BookUser/Logout', // 로그아웃을 처리하는 액션 메서드의 경로
                    type: 'GET', // GET 또는 POST 요청 방식을 선택해야 합니다.
                    success: function (data) {//성공
                        location.href = "/";
                    },
                    error: function (xhr, status, error) {//실패
                        console.log(error); 
                    }
                });
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>