Models/BookClassification.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SrmBook.Models;

public class BookClassification
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int BOOK_NUM { get; set; }

    [Display(Name = "분류명")]
    public string BOOK_CLASS { get; set; }

    [Display(Name = "도서명")]
    public string BOOK_NAME { get; set; }

    [Display(Name = "저자")]
    public string BOOK_WRITER { get; set; }

    [Display(Name = "가격")]
    public int BOOK_PRICE { get; set; }

    [Display(Name = "표지")]
    public byte[] BOOK_IMAGE { get; set; }


}

Models/BookClassificationView.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace SrmBook.Models;
//장르별 검색용 뷰
public class BookClassificationView
{
    public List<BookClassification> BookClassification { get; set; }
    public List<BookInventory> BookInventory { get; set; }
    public SelectList Genre { get; set; }
    public string BookGenre { get; set; }
    public string SearchString { get; set; }
}

Controllers/BookClassificationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SrmBook.Data;
using SrmBook.Models;

namespace SrmBook.Controllers
{
    public class BookClassificationController : Controller
    {
        private readonly BookClassificationContext _context;

        public BookClassificationController(BookClassificationContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string searchString, string BookGenre, int page = 1)
        {
            if (_context.BookClassification == null)
            {
                return Problem("Entity set 'BookClassification' is null.");
            }

            // 검색 쿼리
            IQueryable<string> genreQuery = from m in _context.BookClassification
                                            orderby m.BOOK_CLASS
                                            select m.BOOK_CLASS;

            var BookClassification = from m in _context.BookClassification
                                     select m;

            var BookSearchView = await SearchBooks(searchString, BookGenre, genreQuery, BookClassification);

            // 페이징 처리
            int pageSize = 5; // 페이지당 도서 개수

            var pagedBooks = PaginateBooks(BookSearchView.BookClassification, page, pageSize);

            int totalBooks = BookSearchView.BookClassification.Count(); // 전체 도서 개수

            BookSearchView.PagedBooksClassification = pagedBooks;
            BookSearchView.CurrentPage = page;
            BookSearchView.PageSize = pageSize;
            BookSearchView.TotalBooks = totalBooks;

            return View(BookSearchView);
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BookClassification == null)
            {
                return NotFound();
            }

            var bookClassification = await _context.BookClassification
                .FirstOrDefaultAsync(m => m.BOOK_NUM == id);
            if (bookClassification == null)
            {
                return NotFound();
            }

            return View(bookClassification);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BOOK_NUM,BOOK_CLASS,BOOK_NAME,BOOK_WRITER,BOOK_PRICE,BOOK_IMAGE")] BookClassification bookClassification, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                await ProcessImageFile(bookClassification, imageFile);

                _context.Add(bookClassification);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(bookClassification);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BookClassification == null)
            {
                return NotFound();
            }

            var bookClassification = await _context.BookClassification.FindAsync(id);
            if (bookClassification == null)
            {
                return NotFound();
            }
            return View(bookClassification);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BOOK_NUM,BOOK_CLASS,BOOK_NAME,BOOK_WRITER,BOOK_PRICE")] BookClassification bookClassification, IFormFile imageFile)
        {
            if (id != bookClassification.BOOK_NUM)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await ProcessImageFile(bookClassification, imageFile);
                    _context.Update(bookClassification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookClassificationExists(bookClassification.BOOK_NUM))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookClassification);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BookClassification == null)
            {
                return NotFound();
            }

            var bookClassification = await _context.BookClassification
                .FirstOrDefaultAsync(m => m.BOOK_NUM == id);
            if (bookClassification == null)
            {
                return NotFound();
            }

            return View(bookClassification);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BookClassification == null)
            {
                return Problem("Entity set 'BookClassificationContext.BookClassification' is null.");
            }
            var bookClassification = await _context.BookClassification.FindAsync(id);
            if (bookClassification != null)
            {
                _context.BookClassification.Remove(bookClassification);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookClassificationExists(int id)
        {
            return _context.BookClassification.Any(e => e.BOOK_NUM == id);
        }

        //image파일 바이너리로 변환 메소드
        private async Task ProcessImageFile(BookClassification bookClassification, IFormFile imageFile)
        {
            if (imageFile != null && imageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await imageFile.CopyToAsync(memoryStream);
                    bookClassification.BOOK_IMAGE = memoryStream.ToArray();
                }
            }
        }

        //검색 메소드 
        private async Task<BookSearchView> SearchBooks(string searchString, string BookGenre, IQueryable<string> genreQuery, IQueryable<BookClassification> BookClassification)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                BookClassification = BookClassification.Where(s => s.BOOK_NAME!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(BookGenre))
            {
                BookClassification = BookClassification.Where(x => x.BOOK_CLASS == BookGenre);
            }

            var BookSearchView = new BookSearchView
            {
                Genre = new SelectList(await genreQuery.Distinct().ToListAsync()),
                BookClassification = await BookClassification.ToListAsync()
            };

            return BookSearchView;
        }

        //페이징 처리
        private List<BookClassification> PaginateBooks(List<BookClassification> books, int page, int pageSize)
        {
            return books
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();
        }
    }
}

Views/BookClassification/Create.cshtml
@model SrmBook.Models.BookClassification

@{
    ViewData["Title"] = "Create";
}

<fieldset style="margin-top: 50px;">
    <legend>도서 등록</legend>
</fieldset>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BOOK_IMAGE" class="control-label"></label>
                <input name="imageFile" asp-for="BOOK_IMAGE" type="file" class="form-control"/>
                <span asp-validation-for="BOOK_IMAGE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_CLASS" class="control-label"></label>
                <input asp-for="BOOK_CLASS" class="form-control" />
                <span asp-validation-for="BOOK_CLASS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_NAME" class="control-label"></label>
                <input asp-for="BOOK_NAME" class="form-control" />
                <span asp-validation-for="BOOK_NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_WRITER" class="control-label"></label>
                <input asp-for="BOOK_WRITER" class="form-control" />
                <span asp-validation-for="BOOK_WRITER" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_PRICE" class="control-label"></label>
                <input asp-for="BOOK_PRICE" class="form-control" />
                <span asp-validation-for="BOOK_PRICE" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 5px;">
                <input type="submit" value="등록" class="btn btn-outline-light" />
                <a class="btn btn-outline-light" asp-action="Index">취소</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/BookClassification/Delete.cshtml
@model SrmBook.Models.BookClassification

@{
    ViewData["Title"] = "Delete";
}

<fieldset style="margin-top: 50px;">
    <legend>도서 삭제</legend>
</fieldset>

<p>정말 삭제하시겠습니까?</p>
<p>삭제된 정보는 복구가 불가합니다</p>
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="BOOK_NUM" />
        <input type="submit" value="삭제" class="btn btn-outline-light" />
        <a class="btn btn-outline-light" asp-action="Index">취소</a>
    </form>
</div>

Views/BookClassification/Details.cshtml
@model SrmBook.Models.BookClassification

@{
    ViewData["Title"] = "Details";
    var Key = Context.Session.GetString("USER_TYPE_KEY");
}

<fieldset style="margin-top: 50px;">
    <legend>도서 세부정보</legend>
</fieldset>


<div>
    <dl class="row">
         <dd>
                    @if (Model.BOOK_IMAGE != null)
                    {
                    <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.BOOK_IMAGE)" alt="Book Image"
                        style="max-width: 100px; max-height: 100px;" />
                    }
                    else
                    {
                    <span>이미지가 없습니다</span>
                    }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_CLASS)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BOOK_CLASS)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_NAME)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BOOK_NAME)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_WRITER)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BOOK_WRITER)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_PRICE)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BOOK_PRICE)
        </dd>
    </dl>
</div>
<div style="margin-top: 5px;">
    @if (Key == "admin")
    {
        <a class="btn btn-outline-light" asp-action="Edit" asp-route-id="@Model?.BOOK_NUM">수정</a>
    }
    <a class="btn btn-outline-light" asp-action="Index">목록으로 돌아가기</a>
</div>

Views/BookClassification/Edit.cshtml
@model SrmBook.Models.BookClassification

@{
    ViewData["Title"] = "Edit";
}

<fieldset style="margin-top: 50px;">
    <legend>도서 수정</legend>
</fieldset>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly"  class="text-danger"></div>
            <input type="hidden" asp-for="BOOK_NUM" />
            <div class="form-group">
                <label asp-for="BOOK_IMAGE" class="control-label"></label>
                <input name="imageFile" asp-for="BOOK_IMAGE" type="file" class="form-control"/>
                <span asp-validation-for="BOOK_IMAGE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_CLASS" class="control-label"></label>
                <input asp-for="BOOK_CLASS" class="form-control" />
                <span asp-validation-for="BOOK_CLASS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_NAME" class="control-label"></label>
                <input asp-for="BOOK_NAME" class="form-control" />
                <span asp-validation-for="BOOK_NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_WRITER" class="control-label"></label>
                <input asp-for="BOOK_WRITER" class="form-control" />
                <span asp-validation-for="BOOK_WRITER" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_PRICE" class="control-label"></label>
                <input asp-for="BOOK_PRICE" class="form-control" />
                <span asp-validation-for="BOOK_PRICE" class="text-danger"></span>
            </div>
            <div style="margin-top: 5px;" class="form-group">
                <input type="submit" value="저장" class="btn btn-outline-light" />
                <a class="btn btn-outline-light" asp-action="Index">취소</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BookClassification/Index.cshtml
@model SrmBook.Models.BookSearchView

@{
    ViewData["Title"] = "Index";

    var Key = Context.Session.GetString("USER_TYPE_KEY");
}
<fieldset style="margin-top: 50px;">
    <legend>도서 분류</legend>
</fieldset>

@* 검색 *@
<form asp-controller="BookClassification" asp-action="Index" method="get" style="display: flex;">
    <div style="display: flex;">
        <select style="width:100px;" class="form-select" asp-for="BookGenre" asp-items="Model.Genre">
            <option value="">All</option>
        </select>
        <input style="margin-left: 5px; width:350px;" class="form-control me-sm-2" type="text" name="searchString" />
        <input class="btn btn-outline-light" type="submit" value="검색" />
    </div>
</form>

@if (Key == "admin")
{
    <div style="margin-top: 50px;">
        <a class="btn btn-outline-light" asp-action="Create">도서 등록</a>
    </div>
}

<table style="margin-top: 10px;" class="table table-hover">
    <thead>
        <tr class="table-dark">
            <th scope="col">
                @Html.DisplayNameFor(model => model.PagedBooksClassification[0].BOOK_IMAGE)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PagedBooksClassification[0].BOOK_CLASS)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PagedBooksClassification[0].BOOK_NAME)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PagedBooksClassification[0].BOOK_WRITER)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PagedBooksClassification[0].BOOK_PRICE)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PagedBooksClassification)
        {
            <tr class="table-dark">
                <td scope="row">
                    @if (item.BOOK_IMAGE != null)
                    {
                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(item.BOOK_IMAGE)" alt="Book Image"
                            style="max-width: 70px; max-height: 100px;" />
                    }
                    else
                    {
                        <span>이미지가 없습니다</span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BOOK_CLASS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BOOK_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BOOK_WRITER)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BOOK_PRICE)
                </td>
                <td>
                    <a class="btn btn-outline-light" asp-action="Details" asp-route-id="@item.BOOK_NUM">세부정보</a>
                    @if (Key == "admin")
                    {
                        <a style="margin-left: 5px;" class="btn btn-outline-light" asp-action="Edit"
                            asp-route-id="@item.BOOK_NUM">수정</a>
                        <a style="margin-left: 5px;" class="btn btn-outline-light" asp-action="Delete"
                            asp-route-id="@item.BOOK_NUM">삭제</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@* 페이징 처리 *@
@if (Model.HasPreviousPage || Model.HasNextPage)
{
    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                @if (Model.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link, btn btn-outline-light" href="@Url.Action("Index", new { searchString = Model.SearchString, BookGenre = Model.BookGenre, page = Model.CurrentPage - 1 })">Previous</a>
                    </li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                        <a class="page-link, btn btn-outline-light" href="@Url.Action("Index", new { searchString = Model.SearchString, BookGenre = Model.BookGenre, page = i })">@i</a>
                    </li>
                }
                @if (Model.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link, btn btn-outline-light" href="@Url.Action("Index", new { searchString = Model.SearchString, BookGenre = Model.BookGenre, page = Model.CurrentPage + 1 })">Next</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
}