Models/BookDelivery.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SrmBook.Models;

public class BookDelivery
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Display(Name = "배송 번호")]
    public int DELIVERY_NUM { get; set; }

    [Display(Name = "발주 번호")]
    public int ORDER_NUM { get; set; }

    [Display(Name = "ID")]
    public string USER_ID { get; set; }

    [Display(Name = "배송 날짜")]
    [Required(ErrorMessage = "날짜를 입력하세요")]
    public DateTime DELIVERY_DATE { get; set; }

    [Display(Name = "발주량")]
    [Required(ErrorMessage = "구매 수량을 입력하세요")]
    public int BOOK_QUANTITY { get; set; }

    [Display(Name = "도서 번호")]
    [Required(ErrorMessage = "도서번호를 입력해주세요")]
    public int BOOK_NUM { get; set; }

    [Display(Name = "도서 제목")]
    [Required(ErrorMessage = "도서제목을 입력해주세요")]
    public string BOOK_NAME { get; set; }

    [Display(Name = "주소")]
    [Required(ErrorMessage = "주소를 입력하세요")]
    public string ADDRESS { get; set; }

    [Display(Name = "연락처")]
    [Required(ErrorMessage = "연락처를 입력하세요")]
    [RegularExpression(@"^\d{3}-\d{3,4}-\d{4}$", ErrorMessage = "유효한 전화번호 형식이 아닙니다, -를 입력해주세요")]
    public string TEL { get; set; }
}

Controllers/BookDeliveryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SrmBook.Data;
using SrmBook.Models;

namespace SrmBook.Controllers
{
    public class BookDeliveryController : Controller
    {
        private readonly BookDeliveryContext _context;

        public BookDeliveryController(BookDeliveryContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString, DateTime? searchDate, int? orderPage, int? deliveryPage)
        {

            int itemsPerPage = 5; // 페이지당 항목 수
            int orderCurrentPage = orderPage ?? 1; // 발주 페이지 (기본값: 1)
            int deliveryCurrentPage = deliveryPage ?? 1; // 배송 페이지 (기본값: 1)

            // 로그인한 사용자의 정보를 세션에서 가져옴
            var currentUser = HttpContext.Session.GetString("USER_SESSION_KEY");
            var userType = HttpContext.Session.GetString("USER_TYPE_KEY");

            //배송 검색
            var bookDeliverys = await SearchBookDeliverys(searchString, userType, searchDate, currentUser);
            //발주 검색
            var bookOrders = await SearchBookOrders(searchString, userType, searchDate, currentUser);

            // 페이징 처리 - bookDelivery
            var totalDeliveryItems = bookDeliverys.Count();
            var pagedBookDeliverys = bookDeliverys.Skip((deliveryCurrentPage - 1) * itemsPerPage).Take(itemsPerPage);

            // 페이징 처리 - bookOrder
            var totalOrderItems = bookOrders.Count();
            var pagedBookOrders = bookOrders.Skip((orderCurrentPage - 1) * itemsPerPage).Take(itemsPerPage);

            // 복합ViewModel에 데이터 할당
            var bookDeliveryComposite = new BookDeliveryComposite
            {
                BookOrder = pagedBookOrders,
                BookDelivery = pagedBookDeliverys,
                OrderPageInfo = new BookDeliveryComposite.PageInfo
                {
                    TotalItems = totalOrderItems,
                    CurrentPage = orderCurrentPage,
                    ItemsPerPage = itemsPerPage
                },
                DeliveryPageInfo = new BookDeliveryComposite.PageInfo
                {
                    TotalItems = totalDeliveryItems,
                    CurrentPage = deliveryCurrentPage,
                    ItemsPerPage = itemsPerPage
                },
            };

            return View(bookDeliveryComposite);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BookDelivery == null)
            {
                return NotFound();
            }

            var bookDelivery = await _context.BookDelivery
                .FirstOrDefaultAsync(m => m.DELIVERY_NUM == id);
            if (bookDelivery == null)
            {
                return NotFound();
            }

            return View(bookDelivery);
        }

        public IActionResult Create(int orderNum)
        {
            //발주 정보를 가져오기
            var bookOrder = _context.BookOrder.FirstOrDefault(o => o.ORDER_NUM == orderNum);

            if (bookOrder != null)
            {
                var bookUser = _context.BookUser.FirstOrDefault(u => u.USER_ID == bookOrder.USER_ID);

                if (bookUser != null)
                {
                    var bookDelivery = new BookDelivery
                    {
                        ORDER_NUM = bookOrder.ORDER_NUM,
                        USER_ID = bookOrder.USER_ID,
                        BOOK_QUANTITY = bookOrder.BOOK_QUANTITY,
                        BOOK_NUM = bookOrder.BOOK_NUM,
                        BOOK_NAME = bookOrder.BOOK_NAME,
                        ADDRESS = bookUser.ADDRESS,
                        TEL = bookUser.TEL
                    };

                    return View(bookDelivery);
                }
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DELIVERY_NUM,ORDER_NUM,USER_ID,DELIVERY_DATE,BOOK_QUANTITY,BOOK_NUM,BOOK_NAME,ADDRESS,TEL")] BookDelivery bookDelivery)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookDelivery);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bookDelivery);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BookDelivery == null)
            {
                return NotFound();
            }

            var bookDelivery = await _context.BookDelivery
                .FirstOrDefaultAsync(m => m.DELIVERY_NUM == id);
            if (bookDelivery == null)
            {
                return NotFound();
            }

            return View(bookDelivery);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BookDelivery == null)
            {
                return Problem("Entity set 'BookDeliveryContext.BookDelivery'  is null.");
            }
            var bookDelivery = await _context.BookDelivery.FindAsync(id);
            if (bookDelivery != null)
            {
                _context.BookDelivery.Remove(bookDelivery);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookDeliveryExists(int id)
        {
            return _context.BookDelivery.Any(e => e.DELIVERY_NUM == id);
        }

        //검색 메소드
        private async Task<List<BookDelivery>> SearchBookDeliverys(string searchString, string userType, DateTime? searchDate, string currentUser)
        {
            var bookDeliverys = _context.BookDelivery.AsQueryable();
            if (IsAdminUser(userType))
            {
                // 관리자인 경우 모든 발주를 반환
                bookDeliverys = bookDeliverys.Where(s => true);
            }
            else
            {
                // 일반 사용자인 경우 해당 사용자의 발주만 필터링
                bookDeliverys = bookDeliverys.Where(s => s.USER_ID == currentUser);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                bookDeliverys = bookDeliverys.Where(s => s.BOOK_NAME.Contains(searchString));
            }

            if (searchDate.HasValue)
            {
                DateTime startDate = searchDate.Value.Date;
                DateTime endDate = searchDate.Value.AddDays(1).Date;
                bookDeliverys = bookDeliverys.Where(s => s.DELIVERY_DATE >= startDate && s.DELIVERY_DATE < endDate);
            }

            return await bookDeliverys.ToListAsync();
        }

        //발주 검색 메소드
        private async Task<List<BookOrder>> SearchBookOrders(string searchString, string userType, DateTime? searchDate, string currentUser)
        {
            var bookOrders = _context.BookOrder.AsQueryable();

            if (IsAdminUser(userType))
            {
                // 관리자인 경우 모든 발주를 반환
                bookOrders = bookOrders.Where(s => true);
            }
            else
            {
                // 일반 사용자인 경우 해당 사용자의 발주만 필터링
                bookOrders = bookOrders.Where(s => s.USER_ID == currentUser);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                bookOrders = bookOrders.Where(s => s.BOOK_NAME.Contains(searchString));
            }

            if (searchDate.HasValue)
            {
                DateTime startDate = searchDate.Value.Date;
                DateTime endDate = searchDate.Value.AddDays(1).Date;
                bookOrders = bookOrders.Where(s => s.ORDER_DATE >= startDate && s.ORDER_DATE < endDate);
            }

            return await bookOrders.ToListAsync();
        }

        private bool IsAdminUser(string userType)
        {
            // 세션을 통해 현재 사용자가 관리자인지 여부를 판별
            // 예시: 세션에서 userType 값이 "admin"인 경우에만 관리자로 판별
            return userType == "admin";
        }
    }
}

Views/BookDelivery/Create.cshtml
@model SrmBook.Models.BookDelivery

@{
    ViewData["Title"] = "Create";
}

<fieldset style="margin-top: 50px;">
    <legend>도서 배송</legend>
</fieldset>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ORDER_NUM" class="control-label"></label>
                <input asp-for="ORDER_NUM" class="form-control" readonly />
                <span asp-validation-for="ORDER_NUM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="USER_ID" class="control-label"></label>
                <input asp-for="USER_ID" class="form-control" readonly />
                <span asp-validation-for="USER_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DELIVERY_DATE" class="control-label"></label>
                <input asp-for="DELIVERY_DATE" class="form-control" />
                <span asp-validation-for="DELIVERY_DATE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_QUANTITY" class="control-label"></label>
                <input asp-for="BOOK_QUANTITY" class="form-control" readonly />
                <span asp-validation-for="BOOK_QUANTITY" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_NUM" class="control-label"></label>
                <input asp-for="BOOK_NUM" class="form-control" readonly />
                <span asp-validation-for="BOOK_NUM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BOOK_NAME" class="control-label"></label>
                <input asp-for="BOOK_NAME" class="form-control" readonly />
                <span asp-validation-for="BOOK_NAME" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ADDRESS" class="control-label"></label>
                <input asp-for="ADDRESS" class="form-control" readonly/>
                <span asp-validation-for="ADDRESS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TEL" class="control-label"></label>
                <input asp-for="TEL" class="form-control" readonly/>
                <span asp-validation-for="TEL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/BookDelivery/Delete.cshtml
@model SrmBook.Models.BookDelivery

@{
    ViewData["Title"] = "Delete";
}

<fieldset style="margin-top: 50px;">
    <legend>배송 취소</legend>
</fieldset>

<p>정말 취소하시겠습니까?</p>

<div>   
    <form asp-action="Delete">
        <input type="hidden" asp-for="DELIVERY_NUM" />
        <input type="submit" value="취소" class="btn btn-outline-light" /> |
        <a class="btn btn-outline-light" asp-action="Index">이전</a>
    </form>
</div>

Views/BookDelivery/Details.cshtml
@model SrmBook.Models.BookDelivery

@{
    ViewData["Title"] = "Details";
}


<fieldset style="margin-top: 50px;">
    <legend>배송 상세</legend>
</fieldset>

<div>
    <h4>BookDelivery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ORDER_NUM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ORDER_NUM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.USER_ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.USER_ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DELIVERY_DATE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DELIVERY_DATE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_QUANTITY)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BOOK_QUANTITY)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_NUM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BOOK_NUM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BOOK_NAME)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BOOK_NAME)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ADDRESS)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ADDRESS)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TEL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TEL)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-light" asp-action="Index">이전</a>
</div>

Views/BookDelivery/Index.cshtml
@model SrmBook.Models.BookDeliveryComposite

@{
    ViewData["Title"] = "Index";
    var Key = Context.Session.GetString("USER_SESSION_KEY");
    var admin = Context.Session.GetString("USER_TYPE_KEY");
}

<fieldset style="margin-top: 50px;">
    <legend>배송 내역</legend>
</fieldset>

@* 날짜별 제목별 검색 *@
@using (Html.BeginForm("Index", "BookDelivery", FormMethod.Get))
{
    <div>
        <p style="display: inline-block;">도서 제목으로 검색 :</p>
        <p style="display: inline-block;">
            @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
        </p>
        <p style="display: inline-block;">
            <input class="form-control me-sm-2" type="submit" value="Search" />
        </p>
    </div>

    <div>
        <p style="display: inline-block;">날짜별로 검색 :</p>
        <p style="display: inline-block;">
            @Html.TextBox("searchDate", ViewBag.CurrentDate as string, new { @class = "datepicker form-control" })
        </p>
        <p style="display: inline-block;">
            <input class="form-control me-sm-2" type="submit" value="Search" />
        </p>
    </div>
}
<table style="margin-top: 10px;" class="table table-hover">
    <thead>
        <tr class="table-dark">
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().DELIVERY_NUM)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().ORDER_NUM)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().USER_ID)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().DELIVERY_DATE)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().BOOK_QUANTITY)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().BOOK_NUM)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().BOOK_NAME)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().ADDRESS)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookDelivery.FirstOrDefault().TEL)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BookDelivery)
        {
            if (item.USER_ID == Key || admin == "admin")//로그인한 사람만 보기 가능, 관리자는 전부 보기 가능
            {
                <tr class="table-dark">
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.DELIVERY_NUM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ORDER_NUM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.USER_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DELIVERY_DATE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_QUANTITY)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_NUM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ADDRESS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TEL)
                    </td>
                    <td>
                        @if (admin == "admin")
                        {
                            <a class="btn btn-outline-light" asp-action="Delete" asp-route-id="@item.DELIVERY_NUM">배송취소</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

  <!-- 배송 페이징 -->
    @if (Model.DeliveryPageInfo.TotalPages > 1)
    {
        <div class="pagination">
            @if (Model.DeliveryPageInfo.CurrentPage > 1)
            {
                @Html.ActionLink("이전", "Index", new { deliveryPage = Model.DeliveryPageInfo.CurrentPage - 1 }, new { @class = "btn btn-outline-light" })
            }
            @if (Model.DeliveryPageInfo.CurrentPage < Model.DeliveryPageInfo.TotalPages)
            {
                @Html.ActionLink("다음", "Index", new { deliveryPage = Model.DeliveryPageInfo.CurrentPage + 1 }, new { @class = "btn btn-outline-light" })
            }
        </div>
    }

<fieldset style="margin-top: 50px;">
    <legend>발주 내역</legend>
</fieldset>

@* 발주 테이블 *@
<table style="margin-top: 10px;" class="table table-hover">
    <thead>
        <tr class="table-dark">
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().USER_ID)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().ORDER_DATE)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().BOOK_QUANTITY)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().TOTAL_PRICE)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().BOOK_NAME)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BookOrder.FirstOrDefault().BOOK_NUM)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BookOrder)
        {
            if (item.USER_ID == Key || admin == "admin")//로그인한 사람만 보기 가능, 관리자는 전부 보기 가능
            {
                <tr class="table-dark">
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.USER_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ORDER_DATE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_QUANTITY)
                    </td>
                    @* 소수점 및 콤마 추가 *@
                    <td>
                        @{
                            decimal totalPrice = item.TOTAL_PRICE;
                            int totalPriceInt = Decimal.ToInt32(totalPrice);
                        }
                        @totalPriceInt.ToString("N0")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_NAME)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BOOK_NUM)
                    </td>
                    <td>
                        @if (item.ORDER_CONFIRMED)
                        {
                            <a style="margin-left: 5px;" class="text-success">발주 확인됨</a>
                            @if (admin == "admin")
                            {
                                <a style="margin-left: 5px;" class="btn btn-outline-light" asp-action="Create"
                                    asp-controller="BookDelivery" asp-route-orderNum="@item.ORDER_NUM">배송하기</a>//발주의 order_num의 값을 보내기
                            }
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

  <!-- 발주 페이징 -->
    @if (Model.OrderPageInfo.TotalPages > 1)
    {
        <div class="pagination">
            @if (Model.OrderPageInfo.CurrentPage > 1)
            {
                @Html.ActionLink("이전", "Index", new { orderPage = Model.OrderPageInfo.CurrentPage - 1 }, new { @class = "btn btn-outline-light" })
            }
            @if (Model.OrderPageInfo.CurrentPage < Model.OrderPageInfo.TotalPages)
            {
                @Html.ActionLink("다음", "Index", new { orderPage = Model.OrderPageInfo.CurrentPage + 1 }, new { @class = "btn btn-outline-light" })
            }
        </div>
    }

@* datepicker *@
@section Scripts {
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker();
        });
    </script>
}